In [2]:
print('beginner')
print(12345)

x = 'Daisy'
print(x)

beginner
12345
Daisy


In [3]:
#To create a vector:
x = [1,2,3,4,5,6,7,8,9,10]
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
print(x*2) #this will print vector 'x' two times

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
print(x[1])

2


In [4]:
name = ['Daisy', 'Julie', 'Sophie']
print(name)

['Daisy', 'Julie', 'Sophie']


In [5]:
import numpy as np

array = np.arange(20)
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
x = [1,2,3,4,5,6,7,8,9,10]
x = np.array(x)  # this will turn the vector 'x' above to a numeric vector.
print(x*2)  # we'll get [ 2  4  6  8 10 12 14 16 18 20]


array = np.arange(20) # this will start from 0 and will not include number 20.
print(array*2)

[ 2  4  6  8 10 12 14 16 18 20]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [7]:
y = [1,2,3,4,5,6]

import pandas as pd

y = pd.to_numeric(y)
print(y/2)
print(y**2)

[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [6]:
#import pandas as pd

data = {'X': [1,2,3,4,5,6]}

df = pd.DataFrame(data, columns =['X'])

print(df)
print(df/2)  # this will have the form of a column.


   X
0  1
1  2
2  3
3  4
4  5
5  6
     X
0  0.5
1  1.0
2  1.5
3  2.0
4  2.5
5  3.0


In [1]:
import pandas as pd
data = {'X': [1,2,3,4,5,6], 'Y': [6,5,4,3,2,1]}

df = pd.DataFrame(data, columns =['X', 'Y'])
#print(df**2)  # square of 'data', and this has 2 columns
#print(X)
#list(df)

#df_new = df.rename({'X': 'NewX', 'Y': 'NewY'}, axis='columns') 
df_new = df.rename({'X': 'NewX', 'Y': 'NewY'}, axis=1) 
print(df_new)



   NewX  NewY
0     1     6
1     2     5
2     3     4
3     4     3
4     5     2
5     6     1


In [3]:
import numpy as np
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
matrix = np.array([array1,array2])
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

matrix2 = np.asmatrix([row1,row2,row3]) # make as a matrix
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(matrix2*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [10]:
print(matrix2.shape) #dimension

(3, 3)


In [12]:
print(matrix2.T)  #transpose


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
print(matrix2.I)  # Inverse

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [10]:
print(np.vstack((matrix, array1)) ) # 沿着竖值的方向堆起来

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [5]:
print(np.column_stack((array1, array2)) )

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [24]:
############################    IMPORTING DATA:
###############  CSV DATA

import pandas as pd
data = pd.read_csv(r"/Users/zzy/Desktop/ST2137/Data/Delivery_Time.csv")
print (data)    # the given names of the columns are too long



    Observation  Delivery Time, y  Number of Cases, x1  Distance, x2 (ft)
0             1             16.68                    7                560
1             2             11.50                    3                220
2             3             12.03                    3                340
3             4             14.88                    4                 80
4             5             13.75                    6                150
5             6             18.11                    7                330
6             7              8.00                    2                110
7             8             17.83                    7                210
8             9             79.24                   30               1460
9            10             21.50                    5                605
10           11             40.33                   16                688
11           12             21.00                   10                215
12           13             13.50     

In [25]:

data.columns = ['Obs', 'time', 'cases', 'distance'] # changing the columns' name

print (data)  #the original names have been changed

    Obs   time  cases  distance
0     1  16.68      7       560
1     2  11.50      3       220
2     3  12.03      3       340
3     4  14.88      4        80
4     5  13.75      6       150
5     6  18.11      7       330
6     7   8.00      2       110
7     8  17.83      7       210
8     9  79.24     30      1460
9    10  21.50      5       605
10   11  40.33     16       688
11   12  21.00     10       215
12   13  13.50      4       255
13   14  19.75      6       462
14   15  24.00      9       448
15   16  29.00     10       776
16   17  15.35      6       200
17   18  19.00      7       132
18   19   9.50      3        36
19   20  35.10     17       770
20   21  17.90     10       140
21   22  52.32     26       810
22   23  18.75      9       450
23   24  19.83      8       635
24   25  10.75      4       150


In [26]:
############################    IMPORTING DATA:



###################3  ANOTHER DATA (TEXT data):

text = pd.read_csv(r"/Users/zzy/Desktop/ST2137/Data/ex_1_name.txt", header = 0, sep = " ")
#print(text)
#print(text['CA2'])
CA3 = [1,2,3,4,5,6] #creating a new vector
text['CA3'] = CA3 # adding the new vector to the existing data as a new column
print(text)


   Subject Gender  CA1  CA2 HW  CA3
0       10      M   80   84  A    1
1        7      M   85   89  A    2
2        4      F   90   86  B    3
3       20      M   82   85  B    4
4       25      F   94   94  A    5
5       14      F   88   84  C    6


In [31]:
text = pd.read_csv(r"/Users/zzy/Desktop/ST2137/Data/ex_1_name.txt", header = 0, sep = " ")
#print(text)
new= pd.read_csv(r"/Users/zzy/Desktop/ST2137/Data/ex_1_IQ.txt", header = 0, sep = " ")
print(new['IQ'])

frames = [text, new['IQ']]
#frames = [text, new]  #this will add the 2 columns in ''new'' to the ''text'' dataframe
result = pd.concat(frames, axis=1)
print(result)

0    106
1    112
2    119
3    102
4    125
5    101
Name: IQ, dtype: int64
   Subject Gender  CA1  CA2 HW   IQ
0       10      M   80   84  A  106
1        7      M   85   89  A  112
2        4      F   90   86  B  119
3       20      M   82   85  B  102
4       25      F   94   94  A  125
5       14      F   88   84  C  101


In [4]:
data_text = pd.DataFrame(text, columns = ['Subject', 'CA2'])  #this helps to take out some columns in the data.
print(data_text)
#
print(CA2)  #: this will not work since Python will not know what 'CA2' is.



   Subject  CA2
0       10   84
1        7   89
2        4   86
3       20   85
4       25   94
5       14   84


NameError: name 'CA2' is not defined

In [16]:
def attach(df):
    for col in df.columns:
        globals()[col] = df[col]

attach(data_text)
print(CA2)


0    84
1    89
2    86
3    85
4    94
5    84
Name: CA2, dtype: int64


In [5]:
print(data)


    Obs   time  cases  distance
0     1  16.68      7       560
1     2  11.50      3       220
2     3  12.03      3       340
3     4  14.88      4        80
4     5  13.75      6       150
5     6  18.11      7       330
6     7   8.00      2       110
7     8  17.83      7       210
8     9  79.24     30      1460
9    10  21.50      5       605
10   11  40.33     16       688
11   12  21.00     10       215
12   13  13.50      4       255
13   14  19.75      6       462
14   15  24.00      9       448
15   16  29.00     10       776
16   17  15.35      6       200
17   18  19.00      7       132
18   19   9.50      3        36
19   20  35.10     17       770
20   21  17.90     10       140
21   22  52.32     26       810
22   23  18.75      9       450
23   24  19.83      8       635
24   25  10.75      4       150


In [17]:
print(data['Obs'])


0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
Name: Obs, dtype: int64


In [18]:
data = pd.DataFrame(data) 
def attach(df):
    for col in df.columns:
        globals()[col] = df[col]

attach(data)


In [19]:
print(cases)

0      7
1      3
2      3
3      4
4      6
5      7
6      2
7      7
8     30
9      5
10    16
11    10
12     4
13     6
14     9
15    10
16     6
17     7
18     3
19    17
20    10
21    26
22     9
23     8
24     4
Name: cases, dtype: int64


In [20]:
import os
os.getcwd()


'C:\\Users\\65979'

In [21]:
f = open("ex_1_name.txt", "r")
f = f.read()
print(f)
print(f['Subject'])


Subject Gender CA1 CA2 HW
10 M 80 84 A
7 M 85 89 A
4 F 90 86 B
20 M 82 85 B
25 F 94 94 A
14 F 88 84 C


TypeError: string indices must be integers

In [22]:
x= 1
y = 2
print('x > y is',x>y)

print('x < y is',x<y)

print('x == y is',x==y)

print('x != y is',x!=y)

print('x >= y is',x>=y)

print('x <=y is', x<=y) 

x > y is False
x < y is True
x == y is False
x != y is True
x >= y is False
x <=y is True


In [23]:
x = True
y = False

print('x and y is',x and y)

print('x or y is',x or y)

print('not x is',not x)

x and y is False
x or y is True
not x is False


In [24]:
x = True
y = False

#   x and y means: both x and y happen the same

print(x and y)

False


In [25]:
x = True
y = False

print(x or y)

True


In [3]:
x = -5
if x>0:
    print("a")
elif x>100: 
    print("so large")

In [26]:
print('x < y is',x<y)

x < y is False


In [16]:
x = 10
y = 2

if x<=0:
    print('x is negative')
elif x<=5:
    print('x is positive but less than 5')
else:
    print('x is greater than 5')

x is greater than 5


In [17]:
x = float(input("Enter a number for x: ")) 
y = float(input("Enter a number for y: ")) 
if x == y: 
    print("x and y are equal") 
if y != 0: 
    print("therefore, x / y is", x/y) 
elif x < y: 
    print("x is smaller") 
else: 
    print("y is smaller") 
print("thanks!") 

Enter a number for x: 1231
Enter a number for y: 141234
therefore, x / y is 0.008716031550476514
thanks!


In [13]:
i = 1
while i<=100:
    print('i = ',i,' less than 5')
    if i == 3:
        break
    i = i+1

i =  1  less than 5
i =  2  less than 5
i =  3  less than 5


In [21]:
i = 0
s = 0
while i < 6:
    s = s + i
    i += 1
    if i == 3:
        print('skip')
        continue
    print(s)

0
1
skip
6
10
15


In [49]:
x = 0
test = True
while test == True: 
    x = x+1
    if x<6:
        test = True
    else: 
        test = False
    print(x**2, test)
    
    

1 True
4 True
9 True
16 True
25 True
36 False


In [32]:
S = 0
for i in range(10): # i from 0 to 9
    S = S+i
    print('The sum of the first ',i, 'numbers =',S)

The sum of the first  0 numbers = 0
The sum of the first  1 numbers = 1
The sum of the first  2 numbers = 3
The sum of the first  3 numbers = 6
The sum of the first  4 numbers = 10
The sum of the first  5 numbers = 15
The sum of the first  6 numbers = 21
The sum of the first  7 numbers = 28
The sum of the first  8 numbers = 36
The sum of the first  9 numbers = 45


In [88]:
S = 0
for i in range(1,10,2): 
    S = S+i
    #print(S)
print('sum of all the odd numbers less than 10 is ', S)

sum of all the odd numbers less than 10 is  25


In [38]:
S = 0
for i in range(11): 
    S = S + i
    if i == 6:
        break
    print(S)
    
print('sum of first',i, 'integers is ',S)

0
1
3
6
10
15
sum of first 6 integers is  21


In [84]:
#S = 0
def func_1(S):
    for i in range(11): 
        S = S + i
        if i == 6:
            break
        print(S)
    return(S)
    
    

#func_1(2)
out = print(func_1(0))


0
1
3
6
10
15
21


In [28]:
cube = 27 
epsilon = 0.01 # can change smaller or larger
guess = 0.0 
increment = 0.01 # can change smaller or larger
num_guesses = 0 
while abs(guess**3 - cube) >= epsilon: 
    guess += increment 
    num_guesses += 1 
print('num_guesses =', num_guesses) 
if abs(guess**3 - cube) >= epsilon: 
    print('Failed on cube root of', cube) 
else: 
    print(guess, 'is close to the cube root of', cube)

num_guesses = 300
2.99999999999998 is close to the cube root of 27


In [35]:
import numpy as np
import statistics as st
from statistics import mean
from statistics import median
from statistics import variance
import math

x = [20,3,4,5,8,12,1]
y = [5,6,3,2,80,10,9]
max(x)
min(x)
len(x)
sum(x)
mean(x)
median(x)
variance(x)
sorted(x)
np.corrcoef(x, y)

math.sqrt(9)



3.0

In [36]:
t = (2,3,'abs',5)
t[0]

2

In [38]:
t = (2,3,'abs',5)
t[0] = 1 # change the first element to '1'
print(t)

TypeError: 'tuple' object does not support item assignment

In [39]:
t = [2,3,'abs',5]
t[0] = 1 # change the first element to '1'
print(t)

[1, 3, 'abs', 5]


In [40]:
def f_sum(x):
    return(sum(x))
x = [20,3,4,5,8,12,1]
f_sum(x)

53

In [76]:

type(x)

variance(x)


   Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C


27.1

In [3]:
import math
from statistics import variance
import pandas as pd

def f_se(x):
    se = math.sqrt(variance(x)/len(x))
    return(se)

text = pd.read_csv(r"C:\Data\ex_1_name.txt", header = 0, sep = " ")
x = text['CA1']

print(f_se(x))

2.1252450839060106


In [7]:
text = pd.read_csv(r"C:\Data\ex_1_name.txt", header = 0, sep = " ")
print(text)
x = text['CA1'] # the list that we want to save to a text file
print(x)

   Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C
0    80
1    85
2    90
3    82
4    94
5    88
Name: CA1, dtype: int64


In [123]:
f = open('test.txt','w')
for i in x:
    f.write(str(i) + '\n') 
f.close()


In [8]:

# #########   OR: write the list `x' to a csv file:    
    
x.to_csv('test.csv')

#try to read the file `test' that we just save:
t = pd.read_csv('test.csv')
print(t)  #correct as we want


   Unnamed: 0  CA1
0           0   80
1           1   85
2           2   90
3           3   82
4           4   94
5           5   88


In [124]:
y = pd.read_csv("test.txt", header = None)
print(y)
y.columns = ['first CA'] #name the column
print(y)

    0
0  80
1  85
2  90
3  82
4  94
5  88
   first CA
0        80
1        85
2        90
3        82
4        94
5        88


In [4]:
text = pd.read_csv(r"C:\Data\ex_1_name.txt", header = 0, sep = " ")
text = pd.DataFrame(text)
print(text)

   Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C


In [6]:
#  Write the file 'text' to a csv file called 'test2'
text.to_csv("C:/Data/test2.csv")

# check if the the data was saved correctly:
test = pd.read_csv("C:/Data/test2.csv")

print(test)  #correct



   Unnamed: 0  Subject Gender  CA1  CA2 HW
0           0       10      M   80   84  A
1           1        7      M   85   89  A
2           2        4      F   90   86  B
3           3       20      M   82   85  B
4           4       25      F   94   94  A
5           5       14      F   88   84  C
